apiVersion: v1
kind: Pod

metadata:
  name: simple-app-pod
  labels:
    app: simple-app
    environment: dev

spec:

  volumes:
  - name: shared-data
    emptyDir: {}

  initContainers:
  - name: create-frontend-page
    image: busybox
    command:
    - sh
    - -c
    - |
      cat <<EOF > /shared/index.html
      <!DOCTYPE html>
      <html>
      <head>
          <title>Simple App</title>
      </head>
      <body>
          <h1>Frontend Application</h1>

          <button onclick="getMessage()">
            Get Message
          </button>

          <h2 id="result"></h2>

          <script>
          async function getMessage() {
              const response = await fetch('http://localhost:5000/api/message');
              const data = await response.json();
              document.getElementById('result').innerHTML = data.message;
          }
          </script>

      </body>
      </html>
      EOF

    volumeMounts:
    - name: shared-data
      mountPath: /shared

  containers:

  - name: backend

    image: simple-backend:v1

    imagePullPolicy: Never

    ports:
    - containerPort: 5000

    volumeMounts:
    - name: shared-data
      mountPath: /data

  - name: frontend

    image: nginx:latest

    ports:
    - containerPort: 80

    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
